[package]
edition = "2018"
name = "hello-bc"
version = "0.1.0"
authors = ["Rikard Legge <rikard.legge@gmail.com>"]

[profile.bench]
lto = true

[dependencies]
serde = "1.0.98"
serde_derive = "1.0.98"
bincode = "1.1.4"