[package]
edition = "2018"
name = "leggevm"
version = "0.1.0"
authors = ["Rikard Legge <rikard.legge@gmail.com>"]

[dependencies]

[dev-dependencies]
criterion = "0.3.3"

[[bench]]
name = "interp"
harness = false