[package]
edition = "2018"
name = "legge-vm"
version = "0.1.0"
authors = ["Rikard Legge <rikard.legge@gmail.com>"]

[dependencies]
serde = { version = "1.0.98", features = ["derive"] }
bincode = "1.1.4"