[package]
name = "hello-bc"
version = "0.1.0"
authors = ["Rikard Legge <rikard.legge@gmail.com>"]

[profile.bench]
lto = true

[dependencies]
serde = "1.0.65"
serde_derive = "1.0.65"
bincode = "1.0.0"